Month9/step1
norchah/React-burger pull request #10
Opened 2023-07-19 08:24 UTC by norchah

2023-07-19 08:54 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Правильно используете RTK
- Настроены все редиректы
- Есть механизм обновления токена

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- При открытии ингредиента по прямой ссылке - пустые данные.

<img width="1440" alt="Снимок экрана 2023-07-19 в 11 36 35" src="https://github.com/norchah/React-burger/assets/60173362/c3792500-39d1-4275-802a-1636eca56b28">

- После обновления токена необходимо повторять ранее неудавшийся запроса. Для этого вы можете использовать обертку над `fetch` 

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};

const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options); //делаем запрос
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken(); //обновляем токен
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      localStorage.setItem("accessToken", refreshData.accessToken); //(или в cookies)
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options); //вызываем перезапрос данных
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

**Можно лучше**
- Лого хедера обычно делают ссылкой.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-19 08:54 UTC, andryxxa93 commented on src/components/App/App.jsx
> +          path="/profile"
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-07-19 08:54 UTC, andryxxa93 commented on src/components/pages/forgot-password.jsx
> +  const onChange = (e) => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:
```js
 export function useForm(inputValues) {
   const [values, setValues] = useState(inputValues);
 
   const handleChange = (event) => {
     const {value, name} = event.target;
     setValues({...values, [name]: value});
   };
   return {values, handleChange, setValues};
 }
```
    
Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

 И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:
    
 ```js
   const {values, handleChange, setValues} = useForm({});
 ```

2023-07-19 08:54 UTC, andryxxa93 commented on src/components/pages/forgot-password.jsx
> +  const { email, status } = useSelector((store) => ({
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-07-19 08:54 UTC, andryxxa93 commented on src/components/protected-routes/protected-route-auth.jsx
> +export default function ProtectedRouteAuth({ element }) {
**Можно лучше**

доработайте компонент ProtectedRoute  передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-07-26 16:50 UTC, norchah commented on src/components/App/App.jsx
> +          path="/profile"
+

2023-07-26 21:51 UTC, norchah commented on src/components/protected-routes/protected-route-auth.jsx
> +export default function ProtectedRouteAuth({ element }) {
+

2023-07-26 21:51 UTC, norchah commented on src/components/pages/forgot-password.jsx
> +  const onChange = (e) => {
Не совсем разобрался как использовать в компоненте с инпутами, разберусь

2023-07-26 21:52 UTC, norchah commented on src/components/pages/forgot-password.jsx
> +  const { email, status } = useSelector((store) => ({
Тоже несколько вопросов по реализации, так же доразбираюсь (в коде остались неверные варианты, найду - почищу)

2023-07-27 14:30 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-08-07 12:35 UTC, merged